### ISSUE TITLE
name 'myPDDL' is not defined

### ISSUE THREAD

**Issue by newarney** [Pold87/myPDDL#10]
Hello!

I am trying to use myPDDL in Sublime, but when trying to calculate the distance, I find the following error:
------------------------------------------------------------------------------------------------------------------------
>>> myPDDL-distance
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'myPDDL' is not defined
Exception in thread Thread-6:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "/home/newarney/.config/sublime-text-3/Packages/myPDDL/mypddl.py", line 40, in run
    subprocess.Popen([self.mypddl_cmd, "distance", self.file_name])
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1386, in _execute_child
TypeError: Can't convert 'NoneType' object to str implicitly
------------------------------------------------------------------------------------------------------------------------

I am using Ubuntu 18.04.3 LTS OS (64 bit).

Thank you!

**Comment by Pold87** [comment]
Hi!
Have you tried to run the distance calculation from the command line (i.e.,
not within Sublime Text)? What happens if you type `myPDDL distance
example.pddl`?

**Comment by Pold87** [comment]
Hi!
Have you tried to run the distance calculation from the command line (i.e.,
not within Sublime Text)? What happens if you type `myPDDL distance
example.pddl`?

**Comment by newarney** [comment]
Hello,

I solved the problem. The point is, I'm using Sublime Text 3, but myPDDL path was pointing to Sublime Text 2. The path fix looks like this:
path=~/.config/sublime-text-3/Packages/myPDDL

Thank you!

**Comment by Pold87** [comment]
Thank you for the feedback! I'll update the README so that it points to Sublime 3.

**Comment by anentropic** [comment]
is there not some way to have this line from `myPDDL` file:
```bash
path=~/.config/sublime-text-2/Packages/myPDDL
```
...to just use the current path of the myPDDL file itself?

That would be a better default

Then you can just add 
```bash
export PATH=$PATH:<path to Sublime Text>/Packages/myPDDL
```
to your `.bashrc` as per the README and be done

**Comment by anentropic** [comment]
here is a way for that:
```bash
# Set this path to the myPDDL folder
# Don't use a trailing slash (right: /myPDDL, wrong: /myPDDL/)
path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
```
as found here https://stackoverflow.com/a/246128/202168
