### ISSUE TITLE
Unable to generate Diagrams

### ISSUE THREAD

**Issue by alibeylan** [Pold87/myPDDL#8]
Hi,

I tried generating the diagrams from the terminal and I get this error:

`An error occured.
Please check that: delivery.pddl
is a correct PDDL domain file containing no bracket errors.`

When I check the errors log, I get:

Exception in thread "main" java.io.IOException: Cannot run program "dot" (in directory `/Users/aliciabeylan/Documents/KCL/FYP 4/PDDL"): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at java.base/java.lang.Runtime.exec(Runtime.java:635)
	at clojure.java.shell$sh.doInvoke(shell.clj:116)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:617)
	at me.raynes.fs$exec.doInvoke(fs.clj:472)
	at clojure.lang.RestFn.invoke(RestFn.java:482)
	at mypddl.core$_main.doInvoke(core.clj:286)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at mypddl.core.main(Unknown Source)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:339)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:270)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 10 more`

I followed the instructions but I might have done something wrong. Any ideas?

Thanks!

**Comment by Pold87** [comment]
Hi,

I think you're missing the graphviz package to be able to run the tool `dot` (sorry, it was not stated in the installation instructions yet, I added it now).

By the way, I have not tested myPDDL on macOS, I'm not sure if it works there.

**Comment by alibeylan** [comment]
Thanks! That at least generates _a diagram_ in the diagrams folder! Unfortunately it doesn't generate the diagrams at all. I get a 11x11 white square :/

**Comment by alibeylan** [comment]
Does it support durative-actions? Because I think that might be the problem...

**Comment by Pold87** [comment]
Yes, it should support durative-actions (however, the type diagram just uses the objects and the predicates). 
You can send me your PDDL file If you don't mind (you can also send it per email to volker.strobel87@gmail.com), then I'll check out if it work on my computer.

**Comment by cedricgeissmann** [comment]
Is the error already fixed? I had a similar issue. My diagram was also just an 11 x 11 white png. It turned out that I may not use the word "node" in the PDDL file.

This is just a random guess now, but maybe you should not use words that have a meaning for graphviz. I did not look into the code, it's just a guess based on the one symptom I fixed.
